
name: Modified build
jobs:
  check_format:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |-
        python -m pip install --upgrade pip
        pip install inotify
    - name: Run inotifywait
      run: |-
        python3 -c "
        import inotify.adapters
        import inotify.constants
        import os
        from datetime import datetime, timezone
        with open('/home/runner/inotifywait-log-check_format.csv', 'w') as log_file:
          i = inotify.adapters.InotifyTree('/home/runner/work/sofa-jraft/sofa-jraft', inotify.constants.IN_CREATE | inotify.constants.IN_ACCESS)
          for event in i.event_gen(yield_nones=False):
            (_, type_names, path, filename) = event
            now = datetime.now(timezone.utc).strftime('%Y-%m-%dT%H:%M:%S.%f') + 'Z'
            events = ','.join(type_names)
            log_file.write(f'{now};{path};{filename};{events}\n')
            log_file.flush()
            os.fsync(log_file.fileno())
        " &
    - uses: actions/checkout@v2
    - run: touch optcd-3.txt
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - run: touch optcd-4.txt
    - name: Check format
      run: mvn clean install -DskipTests=true -Dmaven.javadoc.skip=true -B -V && sh
        ./tools/check_format.sh
    - run: touch optcd-5.txt
    - name: Upload inotifywait logs
      uses: actions/upload-artifact@v4
      with:
        name: inotifywait-check_format
        path: /home/runner/inotifywait-log-check_format.csv
    name: check_format
  test_jraft_core:
    needs: check_format
    runs-on: ubuntu-latest
    steps:
    - name: Setup Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |-
        python -m pip install --upgrade pip
        pip install inotify
    - name: Run inotifywait
      run: |-
        python3 -c "
        import inotify.adapters
        import inotify.constants
        import os
        from datetime import datetime, timezone
        with open('/home/runner/inotifywait-log-test_jraft_core.csv', 'w') as log_file:
          i = inotify.adapters.InotifyTree('/home/runner/work/sofa-jraft/sofa-jraft', inotify.constants.IN_CREATE | inotify.constants.IN_ACCESS)
          for event in i.event_gen(yield_nones=False):
            (_, type_names, path, filename) = event
            now = datetime.now(timezone.utc).strftime('%Y-%m-%dT%H:%M:%S.%f') + 'Z'
            events = ','.join(type_names)
            log_file.write(f'{now};{path};{filename};{events}\n')
            log_file.flush()
            os.fsync(log_file.fileno())
        " &
    - uses: actions/checkout@v2
    - run: touch optcd-3.txt
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - run: touch optcd-4.txt
    - name: Maven Test
      run: mvn clean install -DskipTests=true -Dmaven.javadoc.skip=true -B -V && (mvn
        --projects jraft-core test || mvn --projects jraft-core test || mvn --projects
        jraft-core test)
    - run: touch optcd-5.txt
    - name: Upload inotifywait logs
      uses: actions/upload-artifact@v4
      with:
        name: inotifywait-test_jraft_core
        path: /home/runner/inotifywait-log-test_jraft_core.csv
    name: test_jraft_core
  test_rheakv_core:
    needs: check_format
    runs-on: ubuntu-latest
    steps:
    - name: Setup Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |-
        python -m pip install --upgrade pip
        pip install inotify
    - name: Run inotifywait
      run: |-
        python3 -c "
        import inotify.adapters
        import inotify.constants
        import os
        from datetime import datetime, timezone
        with open('/home/runner/inotifywait-log-test_rheakv_core.csv', 'w') as log_file:
          i = inotify.adapters.InotifyTree('/home/runner/work/sofa-jraft/sofa-jraft', inotify.constants.IN_CREATE | inotify.constants.IN_ACCESS)
          for event in i.event_gen(yield_nones=False):
            (_, type_names, path, filename) = event
            now = datetime.now(timezone.utc).strftime('%Y-%m-%dT%H:%M:%S.%f') + 'Z'
            events = ','.join(type_names)
            log_file.write(f'{now};{path};{filename};{events}\n')
            log_file.flush()
            os.fsync(log_file.fileno())
        " &
    - uses: actions/checkout@v2
    - run: touch optcd-3.txt
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - run: touch optcd-4.txt
    - name: Maven Test
      run: mvn clean install -DskipTests=true -Dmaven.javadoc.skip=true -B -V && (mvn
        --projects jraft-rheakv/rheakv-core test || mvn --projects jraft-rheakv/rheakv-core
        test || mvn --projects jraft-rheakv/rheakv-core test)
    - run: touch optcd-5.txt
    - name: Upload inotifywait logs
      uses: actions/upload-artifact@v4
      with:
        name: inotifywait-test_rheakv_core
        path: /home/runner/inotifywait-log-test_rheakv_core.csv
    name: test_rheakv_core
  test_rheakv_pd:
    needs: check_format
    runs-on: ubuntu-latest
    steps:
    - name: Setup Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |-
        python -m pip install --upgrade pip
        pip install inotify
    - name: Run inotifywait
      run: |-
        python3 -c "
        import inotify.adapters
        import inotify.constants
        import os
        from datetime import datetime, timezone
        with open('/home/runner/inotifywait-log-test_rheakv_pd.csv', 'w') as log_file:
          i = inotify.adapters.InotifyTree('/home/runner/work/sofa-jraft/sofa-jraft', inotify.constants.IN_CREATE | inotify.constants.IN_ACCESS)
          for event in i.event_gen(yield_nones=False):
            (_, type_names, path, filename) = event
            now = datetime.now(timezone.utc).strftime('%Y-%m-%dT%H:%M:%S.%f') + 'Z'
            events = ','.join(type_names)
            log_file.write(f'{now};{path};{filename};{events}\n')
            log_file.flush()
            os.fsync(log_file.fileno())
        " &
    - uses: actions/checkout@v2
    - run: touch optcd-3.txt
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - run: touch optcd-4.txt
    - name: Maven Test
      run: mvn clean install -DskipTests=true -Dmaven.javadoc.skip=true -B -V && (mvn
        --projects jraft-rheakv/rheakv-pd test || mvn --projects jraft-rheakv/rheakv-pd
        test || mvn --projects jraft-rheakv/rheakv-pd test)
    - run: touch optcd-5.txt
    - name: Upload inotifywait logs
      uses: actions/upload-artifact@v4
      with:
        name: inotifywait-test_rheakv_pd
        path: /home/runner/inotifywait-log-test_rheakv_pd.csv
    name: test_rheakv_pd
  test_rpc_grpc_impl:
    needs: check_format
    runs-on: ubuntu-latest
    steps:
    - name: Setup Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |-
        python -m pip install --upgrade pip
        pip install inotify
    - name: Run inotifywait
      run: |-
        python3 -c "
        import inotify.adapters
        import inotify.constants
        import os
        from datetime import datetime, timezone
        with open('/home/runner/inotifywait-log-test_rpc_grpc_impl.csv', 'w') as log_file:
          i = inotify.adapters.InotifyTree('/home/runner/work/sofa-jraft/sofa-jraft', inotify.constants.IN_CREATE | inotify.constants.IN_ACCESS)
          for event in i.event_gen(yield_nones=False):
            (_, type_names, path, filename) = event
            now = datetime.now(timezone.utc).strftime('%Y-%m-%dT%H:%M:%S.%f') + 'Z'
            events = ','.join(type_names)
            log_file.write(f'{now};{path};{filename};{events}\n')
            log_file.flush()
            os.fsync(log_file.fileno())
        " &
    - uses: actions/checkout@v2
    - run: touch optcd-3.txt
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - run: touch optcd-4.txt
    - name: Maven Test
      run: mvn clean install -DskipTests=true -Dmaven.javadoc.skip=true -B -V && (mvn
        --projects jraft-extension/rpc-grpc-impl test || mvn --projects jraft-extension/rpc-grpc-impl
        test || mvn --projects jraft-extension/rpc-grpc-impl test)
    - run: touch optcd-5.txt
    - name: Upload inotifywait logs
      uses: actions/upload-artifact@v4
      with:
        name: inotifywait-test_rpc_grpc_impl
        path: /home/runner/inotifywait-log-test_rpc_grpc_impl.csv
    name: test_rpc_grpc_impl
  test_storage_java_impl:
    needs: check_format
    runs-on: ubuntu-latest
    steps:
    - name: Setup Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |-
        python -m pip install --upgrade pip
        pip install inotify
    - name: Run inotifywait
      run: |-
        python3 -c "
        import inotify.adapters
        import inotify.constants
        import os
        from datetime import datetime, timezone
        with open('/home/runner/inotifywait-log-test_storage_java_impl.csv', 'w') as log_file:
          i = inotify.adapters.InotifyTree('/home/runner/work/sofa-jraft/sofa-jraft', inotify.constants.IN_CREATE | inotify.constants.IN_ACCESS)
          for event in i.event_gen(yield_nones=False):
            (_, type_names, path, filename) = event
            now = datetime.now(timezone.utc).strftime('%Y-%m-%dT%H:%M:%S.%f') + 'Z'
            events = ','.join(type_names)
            log_file.write(f'{now};{path};{filename};{events}\n')
            log_file.flush()
            os.fsync(log_file.fileno())
        " &
    - uses: actions/checkout@v2
    - run: touch optcd-3.txt
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - run: touch optcd-4.txt
    - name: Maven Test
      run: mvn clean install -DskipTests=true -Dmaven.javadoc.skip=true -B -V && (mvn
        --projects jraft-extension/java-log-storage-impl test || mvn --projects jraft-extension/java-log-storage-impl
        test || mvn --projects jraft-extension/java-log-storage-impl test)
    - run: touch optcd-5.txt
    - name: Upload inotifywait logs
      uses: actions/upload-artifact@v4
      with:
        name: inotifywait-test_storage_java_impl
        path: /home/runner/inotifywait-log-test_storage_java_impl.csv
    name: test_storage_java_impl
'on':
- push
- workflow_dispatch
